// Auto generated by chem_gen

#define Z_COLOR_TRANSPARENT 0
#define Z_COLOR_WHITE 1
#define Z_COLOR_BLACK 2
#define Z_COLOR_RED 3
#define Z_COLOR_GREEN 4
#define Z_COLOR_YELLOW 5
#define Z_COLOR_BLUE 6
#define Z_COLOR_BROWN 7
#define Z_COLOR_ORANGE 8
#define Z_COLOR_PINK 9
#define Z_COLOR_PURPLE 10
#define Z_COLOR_GRAY 11

var/list/__z_color_names = list(
	"transparent",
	"white",
	"black",
	"red",
	"green",
	"yellow",
	"blue",
	"brown",
	"orange",
	"pink",
	"purple",
	"gray",
)

var/list/__z_color_hex = list(
	"#FFFFFF00", // transparent
	"#FFFFFF", // white
	"#1A1A1A", // black
	"#CC3333", // red
	"#33CC33", // green
	"#CCCC33", // yellow
	"#3333CC", // blue
	"#8B4513", // brown
	"#FF8C00", // orange
	"#FF69B4", // pink
	"#9932CC", // purple
	"#808080", // gray
)

#define Z_ODOR_NONE 0
#define Z_ODOR_ACRID 1
#define Z_ODOR_PUNGENT 2
#define Z_ODOR_METALLIC 3
#define Z_ODOR_ETHEREAL 4
#define Z_ODOR_ALDEHYDIC 5
#define Z_ODOR_SULPHUROUS 6
#define Z_ODOR_PHENOLIC 7
#define Z_ODOR_SOLVENT 8
#define Z_ODOR_OZONIC 9
#define Z_ODOR_PUTRID 10
#define Z_ODOR_RANCID 11
#define Z_ODOR_MUSTY 12
#define Z_ODOR_AMMONIACAL 13
#define Z_ODOR_MUSKY 14
#define Z_ODOR_FERMENTED 15
#define Z_ODOR_FLORAL 16
#define Z_ODOR_HERBACEOUS 17
#define Z_ODOR_WOODY 18
#define Z_ODOR_CAMPHORACEOUS 19
#define Z_ODOR_TERPENE 20
#define Z_ODOR_CITRIC 21
#define Z_ODOR_SPICY 22
#define Z_ODOR_AROMATIC 23
#define Z_ODOR_ESTERY 24
#define Z_ODOR_SWEET 25
#define Z_ODOR_SMOKY 26
#define Z_ODOR_NUTTY 27

var/list/__z_odor_names = list(
	"none",
	"acrid",
	"pungent",
	"metallic",
	"ethereal",
	"aldehydic",
	"sulphurous",
	"phenolic",
	"solvent",
	"ozonic",
	"putrid",
	"rancid",
	"musty",
	"ammoniacal",
	"musky",
	"fermented",
	"floral",
	"herbaceous",
	"woody",
	"camphoraceous",
	"terpene",
	"citric",
	"spicy",
	"aromatic",
	"estery",
	"sweet",
	"smoky",
	"nutty",
)

#define Z_MOL_ACETATE_ION 0
#define Z_MOL_ACETIC_ACID 1
#define Z_MOL_ARGON 2
#define Z_MOL_AZANE 3
#define Z_MOL_BARIUM_DICHLORIDE 4
#define Z_MOL_BARIUM_ION 5
#define Z_MOL_BARIUM_SULFATE 6
#define Z_MOL_CALCIUM_CARBONATE 7
#define Z_MOL_CALCIUM_ION 8
#define Z_MOL_CARBON_DIOXIDE 9
#define Z_MOL_CARBONATE_ION 10
#define Z_MOL_CHLORIDE_ION 11
#define Z_MOL_DICHLOROMETHANE 12
#define Z_MOL_DISODIUM_SULFATE 13
#define Z_MOL_ETHANOL 14
#define Z_MOL_GRAPHITE 15
#define Z_MOL_HYDROGEN_ION 16
#define Z_MOL_NITROGEN 17
#define Z_MOL_OXIDANE 18
#define Z_MOL_OXYGEN 19
#define Z_MOL_SODIUM_CHLORIDE 20
#define Z_MOL_SODIUM_ION 21
#define Z_MOL_SULFATE_ION 22

var/list/__z_molecule_names = list(
	"Acetate ion",
	"Acetic Acid",
	"Argon",
	"Ammonia",
	"Barium Dichloride",
	"Ba+",
	"Barium Sulfate",
	"Calcium Carbonate",
	"Ca+",
	"Carbon Dioxide",
	"CO-",
	"Cl-",
	"Dichloromethane",
	"Disodium Sulfate",
	"Ethanol",
	"Graphite",
	"Hydrogen+",
	"Nitrogen",
	"Water",
	"Oxygen",
	"Sodium Chloride",
	"Na+",
	"SO4-",
)

/datum/molecule_meta
	/// Molecular weight in g/mol (Daltons).
	var/weight
	/// Mass density in g/cm³ at 25°C and 1 atm.
	var/density

/datum/molecule_meta/proc/get_moles_per_liter()
	return (1000.0 * density) / weight

var/list/__z_molecules_meta = newlist(\
	/datum/molecule_meta {
		weight = 59.044;
		density = 1;
	},
	/datum/molecule_meta {
		weight = 60.052;
		density = 1.049;
	},
	/datum/molecule_meta {
		weight = 39.948;
		density = 0.001633;
	},
	/datum/molecule_meta {
		weight = 17.031;
		density = 0.73;
	},
	/datum/molecule_meta {
		weight = 208.233;
		density = 3.86;
	},
	/datum/molecule_meta {
		weight = 137.327;
		density = 1;
	},
	/datum/molecule_meta {
		weight = 233.39;
		density = 4.49;
	},
	/datum/molecule_meta {
		weight = 100.086;
		density = 2.71;
	},
	/datum/molecule_meta {
		weight = 40.078;
		density = 1.55;
	},
	/datum/molecule_meta {
		weight = 44.01;
		density = 0.001799;
	},
	/datum/molecule_meta {
		weight = 60.008;
		density = 1;
	},
	/datum/molecule_meta {
		weight = 35.453;
		density = 1.56;
	},
	/datum/molecule_meta {
		weight = 84.93;
		density = 1.322;
	},
	/datum/molecule_meta {
		weight = 142.042;
		density = 2.66;
	},
	/datum/molecule_meta {
		weight = 46.07;
		density = 0.79;
	},
	/datum/molecule_meta {
		weight = 12.011;
		density = 2.26;
	},
	/datum/molecule_meta {
		weight = 1.008;
		density = 1;
	},
	/datum/molecule_meta {
		weight = 28.014;
		density = 0.001145;
	},
	/datum/molecule_meta {
		weight = 18.015;
		density = 0.997;
	},
	/datum/molecule_meta {
		weight = 31.998;
		density = 0.001308;
	},
	/datum/molecule_meta {
		weight = 58.44;
		density = 2.165;
	},
	/datum/molecule_meta {
		weight = 22.99;
		density = 0.968;
	},
	/datum/molecule_meta {
		weight = 96.06;
		density = 1;
	},
)

var/list/__molecules_cost = list(
	0,
	494.104,
	0,
	0,
	58600,
	0,
	7237,
	1909.8,
	0,
	0,
	0,
	0,
	383.65,
	1451,
	1072.14,
	67,
	0,
	0,
	42.44,
	0,
	287.7,
	0,
	0,
)
